version: "3.9"

services:
  datanode2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode2
    network_mode: host
    restart: always
    volumes:
      - hadoop_datanode2:/hadoop/dfs/data
    ports:
      - 9864:9864
    environment:
      SERVICE_PRECONDITION: "10.123.252.233:9870"
    env_file:
      - ./hadoop.env

  zookeeper2:
    image: confluentinc/cp-zookeeper:7.2.1
    container_name: zookeeper2
    ports:
      - 2181:2181
    restart: unless-stopped
    network_mode: host
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_SERVERS: 10.123.252.233:2888:3888;10.123.252.200:2888:3888;10.123.252.209:2888:3888

  kafka2:
    image: confluentinc/cp-kafka:7.2.1
    container_name: kafka2
    ports:
      - 9092:9092
    expose:
      - '9092'
    network_mode: host
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 10.123.252.233:2181,10.123.252.200:2181,10.123.252.209:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "EXTERNAL:PLAINTEXT"
      KAFKA_LISTENERS: EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: "EXTERNAL://10.123.252.200:9092"
      KAFKA_INTER_BROKER_LISTENER_NAME: EXTERNAL
      KAFKA_BROKER_ID: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_PARTITION_ASSIGNMENT_STRATEGY: org.apache.kafka.clients.consumer.RoundRobinAssignor
    restart: unless-stopped
    depends_on:
      - zookeeper2

volumes:
  hadoop_datanode2:

networks:
  default:
    name: big-data-network