version: "3.9"

services:
  namenode:
    healthcheck:
      start_period: 50s
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    network_mode: host
    restart: always
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - ./stream-in:/stream-in
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    network_mode: host
    restart: always
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data
    ports:
      - 9864:9864
    environment:
      SERVICE_PRECONDITION: "10.123.252.233:9870"
    env_file:
      - ./hadoop.env

  zookeeper1:
    image: confluentinc/cp-zookeeper:7.2.1
    container_name: zookeeper1
    ports:
      - 2181:2181
    restart: unless-stopped
    network_mode: host
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: 10.123.252.233:2888:3888;10.123.252.200:2888:3888;10.123.252.209:2888:3888

  kafka1:
    image: confluentinc/cp-kafka:7.2.1
    container_name: kafka1
    ports:
      - 29092:29092
      - 9092:9092
    network_mode: host
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 10.123.252.233:2181,10.123.252.200:2181,10.123.252.209:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://10.123.252.233:9092,EXTERNAL://host.docker.internal:29092"
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_PARTITION_ASSIGNMENT_STRATEGY: org.apache.kafka.clients.consumer.RoundRobinAssignor
    restart: unless-stopped
    depends_on:
      - zookeeper1

  kowl:
    image: quay.io/cloudhut/kowl:master # We use the master tag as we want to use the latest features e.g. creation of topics.
    ports:
      - 8000:8080
    restart: unless-stopped
    depends_on:
      - zookeeper1
      - kafka1
    environment:
      KAFKA_BROKERS: 10.123.252.233:9092,10.123.252.200:9092,10.123.252.209:9092

  spark-worker-1:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-1
    ports:
      - 8081:8081
    environment:
      - "SPARK_MASTER=10.123.252.200:7077"
    network_mode: host

volumes:
  hadoop_namenode:
  hadoop_datanode1:

networks:
  default:
    name: big-data-network