version: "3.9"

services:
# Kafka upload topics
  kafka-producer:                                       
    build: 
      context: kafka-producer

# Spark jobs goes here
  spark-event-ingestor:
    depends_on:
      - kafka-producer
    build:
      context: spark-event-ingestor
    environment:
      - ENABLE_INIT_DAEMON=false

  spark-repo-ingestor:
    depends_on:
      - kafka-producer
    build:
      context: spark-repo-ingestor
    environment:
      - ENABLE_INIT_DAEMON=false

  spark-user-ingestor:
    depends_on:
      - kafka-producer
    build:
      context: spark-user-ingestor
    environment:
      - ENABLE_INIT_DAEMON=false

networks:
  default:
    name: big-data-network